[workspace]
authors = ["Mose Schmiedel <mose.schmiedel@stud.htwk-leipzig.de>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "scripts"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
doxygen = ">=1.13.2,<2"
python = ">=3.12,<3.14"
